def register(runtime):
    # kv:// — shared state (SQLite), introspection like env://
    runtime.register(
        "kv://runtime/query/health",
        "python://urikv.handlers:health",
        kind="query",
        operation="kv.health",
    )
    runtime.register(
        "kv://runtime/query/list",
        "python://urikv.handlers:list_items",
        kind="query",
        operation="kv.list",
    )
    runtime.register(
        "kv://runtime/query/discover",
        "python://urikv.handlers:discover",
        kind="query",
        operation="kv.discover",
    )
    runtime.register(
        "kv://{namespace}/key/{key}/query/exists",
        "python://urikv.handlers:key_exists",
        kind="query",
        operation="kv.key.exists",
    )
    runtime.register(
        "kv://{namespace}/key/{key}/query/get",
        "python://urikv.handlers:key_get",
        kind="query",
        operation="kv.key.get",
    )
    runtime.register(
        "kv://{namespace}/prefix/{prefix}/query/keys",
        "python://urikv.handlers:list_items",
        kind="query",
        operation="kv.prefix.keys",
    )
    runtime.register(
        "kv://{namespace}/key/{key}/command/set",
        "python://urikv.handlers:key_set",
        kind="command",
        operation="kv.key.set",
        approval="required",
        side_effects=True,
    )
    runtime.register(
        "kv://{namespace}/key/{key}/command/delete",
        "python://urikv.handlers:key_delete",
        kind="command",
        operation="kv.key.delete",
        approval="required",
        side_effects=True,
    )

    # log:// — read node events and log files (like uri3 log://, local to node)
    runtime.register(
        "log://runtime/query/health",
        "python://urikv.log_handlers:log_health",
        kind="query",
        operation="log.health",
    )
    runtime.register(
        "log://runtime/query/streams",
        "python://urikv.log_handlers:log_streams",
        kind="query",
        operation="log.streams",
    )
    runtime.register(
        "log://{stream}/query/read",
        "python://urikv.log_handlers:log_read",
        kind="query",
        operation="log.read",
    )
    runtime.register(
        "log://{stream}/query/summarize",
        "python://urikv.log_handlers:log_summarize",
        kind="query",
        operation="log.summarize",
    )
    runtime.register(
        "log://file/{path}/query/read",
        "python://urikv.log_handlers:log_read",
        kind="query",
        operation="log.file.read",
    )
